name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ensure install dirs
      run: |
        mkdir -p "$APP_HOME/releases" "$APP_HOME/log"

    - name: Set up Erlang/Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: "1.15"
        otp-version: "26"

    - name: Cache deps and build
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: mix-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          mix-${{ runner.os }}-

    - name: Prepare Mix
      run: |
        mix local.hex --force
        mix local.rebar --force

    - name: Install deps
      run: mix deps.get

    - name: Compile
      run: mix deps.compile

    - name: Build assets
      run: mix assets.deploy

    - name: Create release
      run: mix release --overwrite

    - name: Install release to stable path
      run: |
        rsync -a --delete "_build/prod/rel/$RELEASE_NAME/" "$INSTALL_DIR/$RELEASE_NAME/"
        ln -sfn "$INSTALL_DIR/$RELEASE_NAME" "$CURRENT_LINK"
        echo "BIN=$CURRENT_LINK/bin/$RELEASE_NAME" >> $GITHUB_ENV

    - name: Stop old release
      run: $BIN stop || true

    - name: Run migrations
      run: $BIN eval "Errjordan.Release.migrate"

    - name: Start new release
      run: $BIN start
